/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: wdissector.i

package wdissector

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef void* swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef _gostring_ swig_type_16;
typedef _gostring_ swig_type_17;
typedef _gostring_ swig_type_18;
typedef _gostring_ swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
typedef long long swig_type_23;
typedef _gostring_ swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef _gostring_ swig_type_29;
typedef _gostring_ swig_type_30;
typedef _gostring_ swig_type_31;
typedef _gostring_ swig_type_32;
typedef _gostring_ swig_type_33;
typedef _gostring_ swig_type_34;
typedef _gostring_ swig_type_35;
typedef _gostring_ swig_type_36;
typedef long long swig_type_37;
typedef long long swig_type_38;
typedef long long swig_type_39;
typedef long long swig_type_40;
typedef _gostring_ swig_type_41;
typedef _gostring_ swig_type_42;
typedef _gostring_ swig_type_43;
typedef _gostring_ swig_type_44;
typedef long long swig_type_45;
typedef long long swig_type_46;
typedef _gostring_ swig_type_47;
typedef _gostring_ swig_type_48;
typedef _gostring_ swig_type_49;
typedef _gostring_ swig_type_50;
typedef _gostring_ swig_type_51;
typedef _gostring_ swig_type_52;
typedef _gostring_ swig_type_53;
typedef _gostring_ swig_type_54;
typedef _gostring_ swig_type_55;
typedef _gostring_ swig_type_56;
typedef _gostring_ swig_type_57;
typedef _gostring_ swig_type_58;
typedef _gostring_ swig_type_59;
typedef void* swig_type_60;
typedef void* swig_type_61;
typedef void* swig_type_62;
typedef _gostring_ swig_type_63;
typedef _gostring_ swig_type_64;
typedef void* swig_type_65;
typedef _gostring_ swig_type_66;
typedef _gostring_ swig_type_67;
typedef _gostring_ swig_type_68;
typedef _gostring_ swig_type_69;
typedef _gostring_ swig_type_70;
typedef _gostring_ swig_type_71;
typedef _gostring_ swig_type_72;
typedef _gostring_ swig_type_73;
typedef _gostring_ swig_type_74;
extern void _wrap_Swig_free_wdissector_f377edad665c4a82(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_wdissector_f377edad665c4a82(swig_intgo arg1);
extern swig_intgo _wrap_WD_LOG_LEVEL_NONE_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_LOG_LEVEL_NOISY_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_LOG_LEVEL_DEBUG_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_LOG_LEVEL_INFO_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_LOG_LEVEL_MESSAGE_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_LOG_LEVEL_WARNING_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_LOG_LEVEL_CRITICAL_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_LOG_LEVEL_ERROR_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_LOG_LEVEL_ECHO_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_LOG_LEVEL_LAST_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_MODE_NORMAL_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_MODE_FAST_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_WD_MODE_FULL_wdissector_f377edad665c4a82(void);
extern void _wrap_DEMO_PKT_RRC_CONNECTION_SETUP_set_wdissector_f377edad665c4a82(swig_voidp arg1);
extern swig_voidp _wrap_DEMO_PKT_RRC_CONNECTION_SETUP_get_wdissector_f377edad665c4a82(void);
extern void _wrap_DEMO_PKT_RRC_SETUP_COMPLETE_set_wdissector_f377edad665c4a82(swig_voidp arg1);
extern swig_voidp _wrap_DEMO_PKT_RRC_SETUP_COMPLETE_get_wdissector_f377edad665c4a82(void);
extern void _wrap_DEMO_PKT_RRC_RECONFIGURATION_set_wdissector_f377edad665c4a82(swig_voidp arg1);
extern swig_voidp _wrap_DEMO_PKT_RRC_RECONFIGURATION_get_wdissector_f377edad665c4a82(void);
extern void _wrap_DEMO_PKT_NAS_ATTACH_REQUEST_set_wdissector_f377edad665c4a82(swig_voidp arg1);
extern swig_voidp _wrap_DEMO_PKT_NAS_ATTACH_REQUEST_get_wdissector_f377edad665c4a82(void);
extern char _wrap_wdissector_init_wdissector_f377edad665c4a82(swig_type_1 arg1);
extern void _wrap_wdissector_set_log_level_wdissector_f377edad665c4a82(swig_intgo arg1);
extern void _wrap_wdissector_enable_fast_full_dissection_wdissector_f377edad665c4a82(char arg1);
extern void _wrap_wdissector_enable_full_dissection_wdissector_f377edad665c4a82(char arg1);
extern uintptr_t _wrap_packet_set_protocol_wdissector_f377edad665c4a82(swig_type_2 arg1);
extern uintptr_t _wrap_packet_set_protocol_fast_wdissector_f377edad665c4a82(swig_type_3 arg1);
extern void _wrap_packet_dissect_wdissector_f377edad665c4a82(swig_voidp arg1, swig_intgo arg2);
extern void _wrap_packet_set_direction_wdissector_f377edad665c4a82(swig_intgo arg1);
extern void _wrap_packet_cleanup_wdissector_f377edad665c4a82(void);
extern void _wrap_packet_navigate_wdissector_f377edad665c4a82(swig_intgo arg1, swig_intgo arg2, swig_type_4 arg3);
extern uintptr_t _wrap_wdissector_get_edt_wdissector_f377edad665c4a82(void);
extern swig_type_5 _wrap_wdissector_version_info_wdissector_f377edad665c4a82(void);
extern swig_type_6 _wrap_wdissector_profile_info_wdissector_f377edad665c4a82(void);
extern uintptr_t _wrap_packet_register_condition_wdissector_f377edad665c4a82(swig_type_7 arg1, short arg2);
extern void _wrap_packet_set_condition_wdissector_f377edad665c4a82(short arg1);
extern uintptr_t _wrap_packet_read_condition_wdissector_f377edad665c4a82(short arg1);
extern swig_type_8 _wrap_packet_register_filter_wdissector_f377edad665c4a82(swig_type_9 arg1);
extern void _wrap_packet_set_filter_wdissector_f377edad665c4a82(swig_type_10 arg1);
extern uintptr_t _wrap_packet_read_filter_wdissector_f377edad665c4a82(swig_type_11 arg1);
extern uintptr_t _wrap_packet_register_set_field_hfinfo_wdissector_f377edad665c4a82(swig_type_12 arg1);
extern swig_intgo _wrap_packet_get_field_exists_wdissector_f377edad665c4a82(swig_type_13 arg1);
extern uintptr_t _wrap_packet_has_condition_wdissector_f377edad665c4a82(swig_type_14 arg1);
extern uintptr_t _wrap_packet_get_field_wdissector_f377edad665c4a82(swig_type_15 arg1);
extern uintptr_t _wrap_packet_get_fields_wdissector_f377edad665c4a82(swig_type_16 arg1);
extern swig_type_17 _wrap_packet_get_field_name_wdissector_f377edad665c4a82(swig_type_18 arg1);
extern swig_type_19 _wrap_packet_get_field_string_wdissector_f377edad665c4a82(swig_type_20 arg1);
extern swig_intgo _wrap_packet_get_field_offset_wdissector_f377edad665c4a82(swig_type_21 arg1);
extern swig_intgo _wrap_packet_get_field_size_wdissector_f377edad665c4a82(swig_type_22 arg1);
extern swig_type_23 _wrap_packet_get_field_bitmask_wdissector_f377edad665c4a82(swig_type_24 arg1);
extern swig_intgo _wrap_packet_get_field_encoding_wdissector_f377edad665c4a82(swig_type_25 arg1);
extern swig_intgo _wrap_packet_get_field_type_wdissector_f377edad665c4a82(swig_type_26 arg1);
extern swig_type_27 _wrap_packet_get_field_type_name_wdissector_f377edad665c4a82(swig_type_28 arg1);
extern swig_type_29 _wrap_packet_get_field_encoding_name_wdissector_f377edad665c4a82(swig_type_30 arg1);
extern swig_intgo _wrap_packet_get_field_uint32_wdissector_f377edad665c4a82(swig_type_31 arg1);
extern void _wrap_packet_set_field_hfinfo_wdissector_f377edad665c4a82(uintptr_t arg1);
extern char _wrap_packet_set_field_hfinfo_all_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_intgo _wrap_packet_read_field_exists_hfinfo_wdissector_f377edad665c4a82(uintptr_t arg1);
extern uintptr_t _wrap_packet_read_field_hfinfo_wdissector_f377edad665c4a82(uintptr_t arg1);
extern uintptr_t _wrap_packet_read_fields_hfinfo_wdissector_f377edad665c4a82(uintptr_t arg1);
extern uintptr_t _wrap_packet_register_field_wdissector_f377edad665c4a82(swig_type_32 arg1, short arg2);
extern uintptr_t _wrap_packet_register_set_field_wdissector_f377edad665c4a82(swig_type_33 arg1, short arg2);
extern uintptr_t _wrap_packet_set_field_wdissector_f377edad665c4a82(short arg1);
extern uintptr_t _wrap_packet_read_field_wdissector_f377edad665c4a82(short arg1);
extern uintptr_t _wrap_packet_read_fields_wdissector_f377edad665c4a82(short arg1);
extern uintptr_t _wrap_packet_get_header_info_wdissector_f377edad665c4a82(swig_type_34 arg1);
extern uintptr_t _wrap_packet_read_field_at_wdissector_f377edad665c4a82(uintptr_t arg1, short arg2);
extern swig_type_35 _wrap_packet_read_field_name_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_36 _wrap_packet_read_field_abbrev_wdissector_f377edad665c4a82(uintptr_t arg1);
extern short _wrap_packet_read_field_offset_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_intgo _wrap_packet_read_field_size_wdissector_f377edad665c4a82(uintptr_t arg1);
extern char _wrap_packet_read_field_size_bits_wdissector_f377edad665c4a82(swig_type_37 arg1);
extern swig_type_38 _wrap_packet_read_field_bitmask_wdissector_f377edad665c4a82(uintptr_t arg1);
extern char _wrap_packet_read_field_bitmask_offset_wdissector_f377edad665c4a82(swig_type_39 arg1);
extern char _wrap_packet_read_field_bitmask_offset_msb_wdissector_f377edad665c4a82(swig_type_40 arg1);
extern swig_intgo _wrap_packet_read_field_encoding_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_intgo _wrap_packet_read_field_type_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_41 _wrap_packet_read_field_type_name_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_42 _wrap_packet_read_field_encoding_name_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_43 _wrap_packet_read_field_display_name_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_44 _wrap_packet_read_field_string_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_voidp _wrap_packet_read_field_ustring_wdissector_f377edad665c4a82(uintptr_t arg1);
extern uintptr_t _wrap_packet_read_field_bytes_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_intgo _wrap_packet_read_field_uint32_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_intgo _wrap_packet_read_field_int32_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_45 _wrap_packet_read_field_uint64_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_46 _wrap_packet_read_field_int64_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_47 _wrap_packet_read_value_to_string_wdissector_f377edad665c4a82(swig_intgo arg1, uintptr_t arg2);
extern swig_type_48 _wrap_packet_show_wdissector_f377edad665c4a82(void);
extern swig_type_49 _wrap_packet_summary_wdissector_f377edad665c4a82(void);
extern swig_type_50 _wrap_packet_dissectors_wdissector_f377edad665c4a82(void);
extern swig_type_51 _wrap_packet_dissector_wdissector_f377edad665c4a82(char arg1);
extern swig_intgo _wrap_packet_dissectors_count_wdissector_f377edad665c4a82(void);
extern swig_intgo _wrap_packet_layers_count_wdissector_f377edad665c4a82(void);
extern swig_type_52 _wrap_packet_relevant_fields_wdissector_f377edad665c4a82(void);
extern swig_type_53 _wrap_packet_description_wdissector_f377edad665c4a82(void);
extern char _wrap_packet_direction_wdissector_f377edad665c4a82(void);
extern swig_type_54 _wrap_packet_protocol_wdissector_f377edad665c4a82(void);
extern swig_type_55 _wrap_packet_show_pdml_wdissector_f377edad665c4a82(void);
extern char _wrap_packet_field_summary_wdissector_f377edad665c4a82(swig_voidp arg1, swig_intgo arg2, swig_type_56 arg3);
extern void _wrap_wd_log_g_wdissector_f377edad665c4a82(swig_type_57 arg1);
extern void _wrap_wd_log_y_wdissector_f377edad665c4a82(swig_type_58 arg1);
extern void _wrap_wd_log_r_wdissector_f377edad665c4a82(swig_type_59 arg1);
extern void _wrap_set_wd_log_g_wdissector_f377edad665c4a82(swig_type_60 arg1);
extern void _wrap_set_wd_log_y_wdissector_f377edad665c4a82(swig_type_61 arg1);
extern void _wrap_set_wd_log_r_wdissector_f377edad665c4a82(swig_type_62 arg1);
extern uintptr_t _wrap_wd_init_wdissector_f377edad665c4a82(swig_type_63 arg1);
extern uintptr_t _wrap_wd_get_wdissector_f377edad665c4a82(swig_intgo arg1);
extern void _wrap_wd_free_wdissector_f377edad665c4a82(uintptr_t arg1);
extern void _wrap_wd_reset_wdissector_f377edad665c4a82(uintptr_t arg1);
extern void _wrap_wd_reset_all_wdissector_f377edad665c4a82(void);
extern void _wrap_wd_set_log_level_wdissector_f377edad665c4a82(swig_intgo arg1);
extern void _wrap_wd_packet_dissect_wdissector_f377edad665c4a82(uintptr_t arg1, swig_voidp arg2, swig_intgo arg3);
extern uintptr_t _wrap_wd_set_protocol_wdissector_f377edad665c4a82(uintptr_t arg1, swig_type_64 arg2);
extern void _wrap_wd_set_dissection_mode_wdissector_f377edad665c4a82(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_wd_set_packet_direction_wdissector_f377edad665c4a82(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_wd_set_field_callback_wdissector_f377edad665c4a82(uintptr_t arg1, swig_type_65 arg2);
extern char _wrap_wd_packet_direction_wdissector_f377edad665c4a82(uintptr_t arg1);
extern uintptr_t _wrap_wd_edt_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_66 _wrap_wd_info_version_wdissector_f377edad665c4a82(void);
extern swig_type_67 _wrap_wd_info_profile_wdissector_f377edad665c4a82(void);
extern swig_type_68 _wrap_wd_packet_summary_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_69 _wrap_wd_packet_show_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_70 _wrap_wd_packet_show_pdml_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_intgo _wrap_wd_packet_layers_count_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_intgo _wrap_wd_packet_dissectors_count_wdissector_f377edad665c4a82(uintptr_t arg1);
extern swig_type_71 _wrap_wd_packet_dissector_wdissector_f377edad665c4a82(uintptr_t arg1, char arg2);
extern swig_type_72 _wrap_wd_packet_dissectors_wdissector_f377edad665c4a82(uintptr_t arg1);
extern uintptr_t _wrap_wd_field_wdissector_f377edad665c4a82(swig_type_73 arg1);
extern char _wrap_wd_register_field_wdissector_f377edad665c4a82(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_wd_read_field_wdissector_f377edad665c4a82(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_wd_read_all_fields_wdissector_f377edad665c4a82(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_wd_filter_wdissector_f377edad665c4a82(swig_type_74 arg1);
extern void _wrap_wd_register_filter_wdissector_f377edad665c4a82(uintptr_t arg1, uintptr_t arg2);
extern char _wrap_wd_read_filter_wdissector_f377edad665c4a82(uintptr_t arg1, uintptr_t arg2);
#undef intgo
*/
// #cgo CFLAGS: -Ilibs/wireshark/ -Ilibs/wireshark/include
// #cgo pkg-config: glib-2.0
// #cgo LDFLAGS: -L./bin -Wl,-rpath=$ORIGIN/bin -lwdissector
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_wdissector_f377edad665c4a82(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const WD_TYPE_FIELD int = 0
const WD_TYPE_GROUP int = 1
const WD_TYPE_LAYER int = 2
const WD_DIR_TX int = 0
const WD_DIR_RX int = 1
const WD_DIR_DL int = 0
const WD_DIR_UL int = 1
const WD_DIR_SENT int = 0
const WD_DIR_RECV int = 1
const WD_DIR_ANY int = 3
const WD_0 int = 0
const WD_1 int = 1
const WD_2 int = 2
const WD_3 int = 3
const WD_4 int = 4
const WD_5 int = 5
const WD_6 int = 6
const WD_7 int = 7
const WD_8 int = 8
const WD_9 int = 9
const WD_10 int = 10
const WD_11 int = 11
const WD_12 int = 12
const WD_13 int = 13
const WD_14 int = 14
const WD_15 int = 15
type Enum_SS_wd_log_level int
func _swig_getWD_LOG_LEVEL_NONE() (_swig_ret Enum_SS_wd_log_level) {
	var swig_r Enum_SS_wd_log_level
	swig_r = (Enum_SS_wd_log_level)(C._wrap_WD_LOG_LEVEL_NONE_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_LOG_LEVEL_NONE Enum_SS_wd_log_level = _swig_getWD_LOG_LEVEL_NONE()
func _swig_getWD_LOG_LEVEL_NOISY() (_swig_ret Enum_SS_wd_log_level) {
	var swig_r Enum_SS_wd_log_level
	swig_r = (Enum_SS_wd_log_level)(C._wrap_WD_LOG_LEVEL_NOISY_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_LOG_LEVEL_NOISY Enum_SS_wd_log_level = _swig_getWD_LOG_LEVEL_NOISY()
func _swig_getWD_LOG_LEVEL_DEBUG() (_swig_ret Enum_SS_wd_log_level) {
	var swig_r Enum_SS_wd_log_level
	swig_r = (Enum_SS_wd_log_level)(C._wrap_WD_LOG_LEVEL_DEBUG_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_LOG_LEVEL_DEBUG Enum_SS_wd_log_level = _swig_getWD_LOG_LEVEL_DEBUG()
func _swig_getWD_LOG_LEVEL_INFO() (_swig_ret Enum_SS_wd_log_level) {
	var swig_r Enum_SS_wd_log_level
	swig_r = (Enum_SS_wd_log_level)(C._wrap_WD_LOG_LEVEL_INFO_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_LOG_LEVEL_INFO Enum_SS_wd_log_level = _swig_getWD_LOG_LEVEL_INFO()
func _swig_getWD_LOG_LEVEL_MESSAGE() (_swig_ret Enum_SS_wd_log_level) {
	var swig_r Enum_SS_wd_log_level
	swig_r = (Enum_SS_wd_log_level)(C._wrap_WD_LOG_LEVEL_MESSAGE_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_LOG_LEVEL_MESSAGE Enum_SS_wd_log_level = _swig_getWD_LOG_LEVEL_MESSAGE()
func _swig_getWD_LOG_LEVEL_WARNING() (_swig_ret Enum_SS_wd_log_level) {
	var swig_r Enum_SS_wd_log_level
	swig_r = (Enum_SS_wd_log_level)(C._wrap_WD_LOG_LEVEL_WARNING_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_LOG_LEVEL_WARNING Enum_SS_wd_log_level = _swig_getWD_LOG_LEVEL_WARNING()
func _swig_getWD_LOG_LEVEL_CRITICAL() (_swig_ret Enum_SS_wd_log_level) {
	var swig_r Enum_SS_wd_log_level
	swig_r = (Enum_SS_wd_log_level)(C._wrap_WD_LOG_LEVEL_CRITICAL_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_LOG_LEVEL_CRITICAL Enum_SS_wd_log_level = _swig_getWD_LOG_LEVEL_CRITICAL()
func _swig_getWD_LOG_LEVEL_ERROR() (_swig_ret Enum_SS_wd_log_level) {
	var swig_r Enum_SS_wd_log_level
	swig_r = (Enum_SS_wd_log_level)(C._wrap_WD_LOG_LEVEL_ERROR_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_LOG_LEVEL_ERROR Enum_SS_wd_log_level = _swig_getWD_LOG_LEVEL_ERROR()
func _swig_getWD_LOG_LEVEL_ECHO() (_swig_ret Enum_SS_wd_log_level) {
	var swig_r Enum_SS_wd_log_level
	swig_r = (Enum_SS_wd_log_level)(C._wrap_WD_LOG_LEVEL_ECHO_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_LOG_LEVEL_ECHO Enum_SS_wd_log_level = _swig_getWD_LOG_LEVEL_ECHO()
func _swig_getWD_LOG_LEVEL_LAST() (_swig_ret Enum_SS_wd_log_level) {
	var swig_r Enum_SS_wd_log_level
	swig_r = (Enum_SS_wd_log_level)(C._wrap_WD_LOG_LEVEL_LAST_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_LOG_LEVEL_LAST Enum_SS_wd_log_level = _swig_getWD_LOG_LEVEL_LAST()
type Enum_SS_wd_dissection_mode int
func _swig_getWD_MODE_NORMAL() (_swig_ret Enum_SS_wd_dissection_mode) {
	var swig_r Enum_SS_wd_dissection_mode
	swig_r = (Enum_SS_wd_dissection_mode)(C._wrap_WD_MODE_NORMAL_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_MODE_NORMAL Enum_SS_wd_dissection_mode = _swig_getWD_MODE_NORMAL()
func _swig_getWD_MODE_FAST() (_swig_ret Enum_SS_wd_dissection_mode) {
	var swig_r Enum_SS_wd_dissection_mode
	swig_r = (Enum_SS_wd_dissection_mode)(C._wrap_WD_MODE_FAST_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_MODE_FAST Enum_SS_wd_dissection_mode = _swig_getWD_MODE_FAST()
func _swig_getWD_MODE_FULL() (_swig_ret Enum_SS_wd_dissection_mode) {
	var swig_r Enum_SS_wd_dissection_mode
	swig_r = (Enum_SS_wd_dissection_mode)(C._wrap_WD_MODE_FULL_wdissector_f377edad665c4a82())
	return swig_r
}

var WD_MODE_FULL Enum_SS_wd_dissection_mode = _swig_getWD_MODE_FULL()
func SetDEMO_PKT_RRC_CONNECTION_SETUP(arg1 *byte) {
	_swig_i_0 := arg1
	C._wrap_DEMO_PKT_RRC_CONNECTION_SETUP_set_wdissector_f377edad665c4a82(C.swig_voidp(_swig_i_0))
}

func GetDEMO_PKT_RRC_CONNECTION_SETUP() (_swig_ret *byte) {
	var swig_r *byte
	swig_r = (*byte)(C._wrap_DEMO_PKT_RRC_CONNECTION_SETUP_get_wdissector_f377edad665c4a82())
	return swig_r
}

func SetDEMO_PKT_RRC_SETUP_COMPLETE(arg1 *byte) {
	_swig_i_0 := arg1
	C._wrap_DEMO_PKT_RRC_SETUP_COMPLETE_set_wdissector_f377edad665c4a82(C.swig_voidp(_swig_i_0))
}

func GetDEMO_PKT_RRC_SETUP_COMPLETE() (_swig_ret *byte) {
	var swig_r *byte
	swig_r = (*byte)(C._wrap_DEMO_PKT_RRC_SETUP_COMPLETE_get_wdissector_f377edad665c4a82())
	return swig_r
}

func SetDEMO_PKT_RRC_RECONFIGURATION(arg1 *byte) {
	_swig_i_0 := arg1
	C._wrap_DEMO_PKT_RRC_RECONFIGURATION_set_wdissector_f377edad665c4a82(C.swig_voidp(_swig_i_0))
}

func GetDEMO_PKT_RRC_RECONFIGURATION() (_swig_ret *byte) {
	var swig_r *byte
	swig_r = (*byte)(C._wrap_DEMO_PKT_RRC_RECONFIGURATION_get_wdissector_f377edad665c4a82())
	return swig_r
}

func SetDEMO_PKT_NAS_ATTACH_REQUEST(arg1 *byte) {
	_swig_i_0 := arg1
	C._wrap_DEMO_PKT_NAS_ATTACH_REQUEST_set_wdissector_f377edad665c4a82(C.swig_voidp(_swig_i_0))
}

func GetDEMO_PKT_NAS_ATTACH_REQUEST() (_swig_ret *byte) {
	var swig_r *byte
	swig_r = (*byte)(C._wrap_DEMO_PKT_NAS_ATTACH_REQUEST_get_wdissector_f377edad665c4a82())
	return swig_r
}

func Wdissector_init(arg1 string) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_wdissector_init_wdissector_f377edad665c4a82(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Wdissector_set_log_level(arg1 Enum_SS_wd_log_level) {
	_swig_i_0 := arg1
	C._wrap_wdissector_set_log_level_wdissector_f377edad665c4a82(C.swig_intgo(_swig_i_0))
}

func Wdissector_enable_fast_full_dissection(arg1 byte) {
	_swig_i_0 := arg1
	C._wrap_wdissector_enable_fast_full_dissection_wdissector_f377edad665c4a82(C.char(_swig_i_0))
}

func Wdissector_enable_full_dissection(arg1 byte) {
	_swig_i_0 := arg1
	C._wrap_wdissector_enable_full_dissection_wdissector_f377edad665c4a82(C.char(_swig_i_0))
}

func Packet_set_protocol(arg1 string) (_swig_ret Gboolean) {
	var swig_r Gboolean
	_swig_i_0 := arg1
	swig_r = (Gboolean)(SwigcptrGboolean(C._wrap_packet_set_protocol_wdissector_f377edad665c4a82(*(*C.swig_type_2)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_set_protocol_fast(arg1 string) (_swig_ret Gboolean) {
	var swig_r Gboolean
	_swig_i_0 := arg1
	swig_r = (Gboolean)(SwigcptrGboolean(C._wrap_packet_set_protocol_fast_wdissector_f377edad665c4a82(*(*C.swig_type_3)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_dissect(arg1 *byte, arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_packet_dissect_wdissector_f377edad665c4a82(C.swig_voidp(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Packet_set_direction(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_packet_set_direction_wdissector_f377edad665c4a82(C.swig_intgo(_swig_i_0))
}

func Packet_cleanup() {
	C._wrap_packet_cleanup_wdissector_f377edad665c4a82()
}

func Packet_navigate(arg1 uint, arg2 uint, arg3 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_packet_navigate_wdissector_f377edad665c4a82(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_type_4(_swig_i_2))
}

func Wdissector_get_edt() (_swig_ret Epan_dissect_t) {
	var swig_r Epan_dissect_t
	swig_r = (Epan_dissect_t)(SwigcptrEpan_dissect_t(C._wrap_wdissector_get_edt_wdissector_f377edad665c4a82()))
	return swig_r
}

func Wdissector_version_info() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_wdissector_version_info_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Wdissector_profile_info() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_wdissector_profile_info_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_register_condition(arg1 string, arg2 uint16) (_swig_ret Gboolean) {
	var swig_r Gboolean
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Gboolean)(SwigcptrGboolean(C._wrap_packet_register_condition_wdissector_f377edad665c4a82(*(*C.swig_type_7)(unsafe.Pointer(&_swig_i_0)), C.short(_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_set_condition(arg1 uint16) {
	_swig_i_0 := arg1
	C._wrap_packet_set_condition_wdissector_f377edad665c4a82(C.short(_swig_i_0))
}

func Packet_read_condition(arg1 uint16) (_swig_ret Gboolean) {
	var swig_r Gboolean
	_swig_i_0 := arg1
	swig_r = (Gboolean)(SwigcptrGboolean(C._wrap_packet_read_condition_wdissector_f377edad665c4a82(C.short(_swig_i_0))))
	return swig_r
}

func Packet_register_filter(arg1 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_packet_register_filter_wdissector_f377edad665c4a82(*(*C.swig_type_9)(unsafe.Pointer(&_swig_i_0)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_set_filter(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_packet_set_filter_wdissector_f377edad665c4a82(*(*C.swig_type_10)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Packet_read_filter(arg1 string) (_swig_ret Gboolean) {
	var swig_r Gboolean
	_swig_i_0 := arg1
	swig_r = (Gboolean)(SwigcptrGboolean(C._wrap_packet_read_filter_wdissector_f377edad665c4a82(*(*C.swig_type_11)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_register_set_field_hfinfo(arg1 string) (_swig_ret Header_field_info) {
	var swig_r Header_field_info
	_swig_i_0 := arg1
	swig_r = (Header_field_info)(SwigcptrHeader_field_info(C._wrap_packet_register_set_field_hfinfo_wdissector_f377edad665c4a82(*(*C.swig_type_12)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_get_field_exists(arg1 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_packet_get_field_exists_wdissector_f377edad665c4a82(*(*C.swig_type_13)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_has_condition(arg1 string) (_swig_ret Gboolean) {
	var swig_r Gboolean
	_swig_i_0 := arg1
	swig_r = (Gboolean)(SwigcptrGboolean(C._wrap_packet_has_condition_wdissector_f377edad665c4a82(*(*C.swig_type_14)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_get_field(arg1 string) (_swig_ret Field_info) {
	var swig_r Field_info
	_swig_i_0 := arg1
	swig_r = (Field_info)(SwigcptrField_info(C._wrap_packet_get_field_wdissector_f377edad665c4a82(*(*C.swig_type_15)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_get_fields(arg1 string) (_swig_ret GPtrArray) {
	var swig_r GPtrArray
	_swig_i_0 := arg1
	swig_r = (GPtrArray)(SwigcptrGPtrArray(C._wrap_packet_get_fields_wdissector_f377edad665c4a82(*(*C.swig_type_16)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_get_field_name(arg1 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_packet_get_field_name_wdissector_f377edad665c4a82(*(*C.swig_type_18)(unsafe.Pointer(&_swig_i_0)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_get_field_string(arg1 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_packet_get_field_string_wdissector_f377edad665c4a82(*(*C.swig_type_20)(unsafe.Pointer(&_swig_i_0)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_get_field_offset(arg1 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_packet_get_field_offset_wdissector_f377edad665c4a82(*(*C.swig_type_21)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_get_field_size(arg1 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_packet_get_field_size_wdissector_f377edad665c4a82(*(*C.swig_type_22)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_get_field_bitmask(arg1 string) (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_packet_get_field_bitmask_wdissector_f377edad665c4a82(*(*C.swig_type_24)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_get_field_encoding(arg1 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_packet_get_field_encoding_wdissector_f377edad665c4a82(*(*C.swig_type_25)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_get_field_type(arg1 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_packet_get_field_type_wdissector_f377edad665c4a82(*(*C.swig_type_26)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_get_field_type_name(arg1 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_packet_get_field_type_name_wdissector_f377edad665c4a82(*(*C.swig_type_28)(unsafe.Pointer(&_swig_i_0)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_get_field_encoding_name(arg1 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_packet_get_field_encoding_name_wdissector_f377edad665c4a82(*(*C.swig_type_30)(unsafe.Pointer(&_swig_i_0)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_get_field_uint32(arg1 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_packet_get_field_uint32_wdissector_f377edad665c4a82(*(*C.swig_type_31)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_set_field_hfinfo(arg1 Header_field_info) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_packet_set_field_hfinfo_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
}

func Packet_set_field_hfinfo_all(arg1 Header_field_info) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (byte)(C._wrap_packet_set_field_hfinfo_all_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_exists_hfinfo(arg1 Header_field_info) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_packet_read_field_exists_hfinfo_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_hfinfo(arg1 Header_field_info) (_swig_ret Field_info) {
	var swig_r Field_info
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Field_info)(SwigcptrField_info(C._wrap_packet_read_field_hfinfo_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Packet_read_fields_hfinfo(arg1 Header_field_info) (_swig_ret GPtrArray) {
	var swig_r GPtrArray
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (GPtrArray)(SwigcptrGPtrArray(C._wrap_packet_read_fields_hfinfo_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Packet_register_field(arg1 string, arg2 uint16) (_swig_ret Gboolean) {
	var swig_r Gboolean
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Gboolean)(SwigcptrGboolean(C._wrap_packet_register_field_wdissector_f377edad665c4a82(*(*C.swig_type_32)(unsafe.Pointer(&_swig_i_0)), C.short(_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_register_set_field(arg1 string, arg2 uint16) (_swig_ret Gboolean) {
	var swig_r Gboolean
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Gboolean)(SwigcptrGboolean(C._wrap_packet_register_set_field_wdissector_f377edad665c4a82(*(*C.swig_type_33)(unsafe.Pointer(&_swig_i_0)), C.short(_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_set_field(arg1 uint16) (_swig_ret Gboolean) {
	var swig_r Gboolean
	_swig_i_0 := arg1
	swig_r = (Gboolean)(SwigcptrGboolean(C._wrap_packet_set_field_wdissector_f377edad665c4a82(C.short(_swig_i_0))))
	return swig_r
}

func Packet_read_field(arg1 uint16) (_swig_ret Field_info) {
	var swig_r Field_info
	_swig_i_0 := arg1
	swig_r = (Field_info)(SwigcptrField_info(C._wrap_packet_read_field_wdissector_f377edad665c4a82(C.short(_swig_i_0))))
	return swig_r
}

func Packet_read_fields(arg1 uint16) (_swig_ret GPtrArray) {
	var swig_r GPtrArray
	_swig_i_0 := arg1
	swig_r = (GPtrArray)(SwigcptrGPtrArray(C._wrap_packet_read_fields_wdissector_f377edad665c4a82(C.short(_swig_i_0))))
	return swig_r
}

func Packet_get_header_info(arg1 string) (_swig_ret Header_field_info) {
	var swig_r Header_field_info
	_swig_i_0 := arg1
	swig_r = (Header_field_info)(SwigcptrHeader_field_info(C._wrap_packet_get_header_info_wdissector_f377edad665c4a82(*(*C.swig_type_34)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Packet_read_field_at(arg1 GPtrArray, arg2 uint16) (_swig_ret Field_info) {
	var swig_r Field_info
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Field_info)(SwigcptrField_info(C._wrap_packet_read_field_at_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.short(_swig_i_1))))
	return swig_r
}

func Packet_read_field_name(arg1 Field_info) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_packet_read_field_name_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_read_field_abbrev(arg1 Field_info) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_packet_read_field_abbrev_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_read_field_offset(arg1 Field_info) (_swig_ret uint16) {
	var swig_r uint16
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint16)(C._wrap_packet_read_field_offset_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_size(arg1 Field_info) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_packet_read_field_size_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_size_bits(arg1 uint64) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_packet_read_field_size_bits_wdissector_f377edad665c4a82(C.swig_type_37(_swig_i_0)))
	return swig_r
}

func Packet_read_field_bitmask(arg1 Field_info) (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint64)(C._wrap_packet_read_field_bitmask_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_bitmask_offset(arg1 uint64) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_packet_read_field_bitmask_offset_wdissector_f377edad665c4a82(C.swig_type_39(_swig_i_0)))
	return swig_r
}

func Packet_read_field_bitmask_offset_msb(arg1 uint64) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_packet_read_field_bitmask_offset_msb_wdissector_f377edad665c4a82(C.swig_type_40(_swig_i_0)))
	return swig_r
}

func Packet_read_field_encoding(arg1 Field_info) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_packet_read_field_encoding_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_type(arg1 Field_info) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_packet_read_field_type_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_type_name(arg1 Field_info) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_packet_read_field_type_name_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_read_field_encoding_name(arg1 Field_info) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_packet_read_field_encoding_name_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_read_field_display_name(arg1 Field_info) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_packet_read_field_display_name_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_read_field_string(arg1 Field_info) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_packet_read_field_string_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_read_field_ustring(arg1 Field_info) (_swig_ret *byte) {
	var swig_r *byte
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (*byte)(C._wrap_packet_read_field_ustring_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_bytes(arg1 Field_info) (_swig_ret GByteArray) {
	var swig_r GByteArray
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (GByteArray)(SwigcptrGByteArray(C._wrap_packet_read_field_bytes_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Packet_read_field_uint32(arg1 Field_info) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_packet_read_field_uint32_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_int32(arg1 Field_info) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_packet_read_field_int32_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_uint64(arg1 Field_info) (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint64)(C._wrap_packet_read_field_uint64_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_field_int64(arg1 Field_info) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int64)(C._wrap_packet_read_field_int64_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Packet_read_value_to_string(arg1 uint, arg2 Header_field_info) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r_p := C._wrap_packet_read_value_to_string_wdissector_f377edad665c4a82(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_show() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_packet_show_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_summary() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_packet_summary_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_dissectors() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_packet_dissectors_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_dissector(arg1 byte) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_packet_dissector_wdissector_f377edad665c4a82(C.char(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_dissectors_count() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_packet_dissectors_count_wdissector_f377edad665c4a82())
	return swig_r
}

func Packet_layers_count() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_packet_layers_count_wdissector_f377edad665c4a82())
	return swig_r
}

func Packet_relevant_fields() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_packet_relevant_fields_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_description() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_packet_description_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_direction() (_swig_ret byte) {
	var swig_r byte
	swig_r = (byte)(C._wrap_packet_direction_wdissector_f377edad665c4a82())
	return swig_r
}

func Packet_protocol() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_packet_protocol_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_show_pdml() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_packet_show_pdml_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Packet_field_summary(arg1 *byte, arg2 uint, arg3 string) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (byte)(C._wrap_packet_field_summary_wdissector_f377edad665c4a82(C.swig_voidp(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_56)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Wd_log_g(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_wd_log_g_wdissector_f377edad665c4a82(*(*C.swig_type_57)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Wd_log_y(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_wd_log_y_wdissector_f377edad665c4a82(*(*C.swig_type_58)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Wd_log_r(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_wd_log_r_wdissector_f377edad665c4a82(*(*C.swig_type_59)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_wd_log_g(arg1 _swig_fnptr) {
	_swig_i_0 := arg1
	C._wrap_set_wd_log_g_wdissector_f377edad665c4a82(C.swig_type_60(_swig_i_0))
}

func Set_wd_log_y(arg1 _swig_fnptr) {
	_swig_i_0 := arg1
	C._wrap_set_wd_log_y_wdissector_f377edad665c4a82(C.swig_type_61(_swig_i_0))
}

func Set_wd_log_r(arg1 _swig_fnptr) {
	_swig_i_0 := arg1
	C._wrap_set_wd_log_r_wdissector_f377edad665c4a82(C.swig_type_62(_swig_i_0))
}

func Wd_init(arg1 string) (_swig_ret Struct_SS__wd_t) {
	var swig_r Struct_SS__wd_t
	_swig_i_0 := arg1
	swig_r = (Struct_SS__wd_t)(SwigcptrStruct_SS__wd_t(C._wrap_wd_init_wdissector_f377edad665c4a82(*(*C.swig_type_63)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Wd_get(arg1 uint) (_swig_ret Struct_SS__wd_t) {
	var swig_r Struct_SS__wd_t
	_swig_i_0 := arg1
	swig_r = (Struct_SS__wd_t)(SwigcptrStruct_SS__wd_t(C._wrap_wd_get_wdissector_f377edad665c4a82(C.swig_intgo(_swig_i_0))))
	return swig_r
}

func Wd_free(arg1 Struct_SS__wd_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_wd_free_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
}

func Wd_reset(arg1 Struct_SS__wd_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_wd_reset_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
}

func Wd_reset_all() {
	C._wrap_wd_reset_all_wdissector_f377edad665c4a82()
}

func Wd_set_log_level(arg1 Enum_SS_wd_log_level) {
	_swig_i_0 := arg1
	C._wrap_wd_set_log_level_wdissector_f377edad665c4a82(C.swig_intgo(_swig_i_0))
}

func Wd_packet_dissect(arg1 Struct_SS__wd_t, arg2 *byte, arg3 uint) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_wd_packet_dissect_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func Wd_set_protocol(arg1 Struct_SS__wd_t, arg2 string) (_swig_ret Gboolean) {
	var swig_r Gboolean
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Gboolean)(SwigcptrGboolean(C._wrap_wd_set_protocol_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), *(*C.swig_type_64)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Wd_set_dissection_mode(arg1 Struct_SS__wd_t, arg2 Enum_SS_wd_dissection_mode) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_wd_set_dissection_mode_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Wd_set_packet_direction(arg1 Struct_SS__wd_t, arg2 uint) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_wd_set_packet_direction_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Wd_set_field_callback(arg1 Struct_SS__wd_t, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_wd_set_field_callback_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.swig_type_65(_swig_i_1))
}

func Wd_packet_direction(arg1 Struct_SS__wd_t) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (byte)(C._wrap_wd_packet_direction_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Wd_edt(arg1 Struct_SS__wd_t) (_swig_ret Epan_dissect_t) {
	var swig_r Epan_dissect_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Epan_dissect_t)(SwigcptrEpan_dissect_t(C._wrap_wd_edt_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Wd_info_version() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_wd_info_version_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Wd_info_profile() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_wd_info_profile_wdissector_f377edad665c4a82()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Wd_packet_summary(arg1 Struct_SS__wd_t) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_wd_packet_summary_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Wd_packet_show(arg1 Struct_SS__wd_t) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_wd_packet_show_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Wd_packet_show_pdml(arg1 Struct_SS__wd_t) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_wd_packet_show_pdml_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Wd_packet_layers_count(arg1 Struct_SS__wd_t) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_wd_packet_layers_count_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Wd_packet_dissectors_count(arg1 Struct_SS__wd_t) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_wd_packet_dissectors_count_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Wd_packet_dissector(arg1 Struct_SS__wd_t, arg2 byte) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r_p := C._wrap_wd_packet_dissector_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Wd_packet_dissectors(arg1 Struct_SS__wd_t) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_wd_packet_dissectors_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Wd_field(arg1 string) (_swig_ret Header_field_info) {
	var swig_r Header_field_info
	_swig_i_0 := arg1
	swig_r = (Header_field_info)(SwigcptrHeader_field_info(C._wrap_wd_field_wdissector_f377edad665c4a82(*(*C.swig_type_73)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Wd_register_field(arg1 Struct_SS__wd_t, arg2 Header_field_info) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (byte)(C._wrap_wd_register_field_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Wd_read_field(arg1 Struct_SS__wd_t, arg2 Header_field_info) (_swig_ret Field_info) {
	var swig_r Field_info
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Field_info)(SwigcptrField_info(C._wrap_wd_read_field_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Wd_read_all_fields(arg1 Struct_SS__wd_t, arg2 Header_field_info) (_swig_ret GPtrArray) {
	var swig_r GPtrArray
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (GPtrArray)(SwigcptrGPtrArray(C._wrap_wd_read_all_fields_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Wd_filter(arg1 string) (_swig_ret Struct_SS_epan_dfilter) {
	var swig_r Struct_SS_epan_dfilter
	_swig_i_0 := arg1
	swig_r = (Struct_SS_epan_dfilter)(SwigcptrStruct_SS_epan_dfilter(C._wrap_wd_filter_wdissector_f377edad665c4a82(*(*C.swig_type_74)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Wd_register_filter(arg1 Struct_SS__wd_t, arg2 Struct_SS_epan_dfilter) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_wd_register_filter_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Wd_read_filter(arg1 Struct_SS__wd_t, arg2 Struct_SS_epan_dfilter) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (byte)(C._wrap_wd_read_filter_wdissector_f377edad665c4a82(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}


type SwigcptrGPtrArray uintptr
type GPtrArray interface {
	Swigcptr() uintptr;
}
func (p SwigcptrGPtrArray) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrHeader_field_info uintptr
type Header_field_info interface {
	Swigcptr() uintptr;
}
func (p SwigcptrHeader_field_info) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrField_info uintptr
type Field_info interface {
	Swigcptr() uintptr;
}
func (p SwigcptrField_info) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrGboolean uintptr
type Gboolean interface {
	Swigcptr() uintptr;
}
func (p SwigcptrGboolean) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrEpan_dissect_t uintptr
type Epan_dissect_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrEpan_dissect_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrGByteArray uintptr
type GByteArray interface {
	Swigcptr() uintptr;
}
func (p SwigcptrGByteArray) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_epan_dfilter uintptr
type Struct_SS_epan_dfilter interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_epan_dfilter) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS__wd_t uintptr
type Struct_SS__wd_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS__wd_t) Swigcptr() uintptr {
	return uintptr(p)
}

